/**
 * agent-changelog Webhook Handler
 *
 * Processes GitHub PR merge events and generates changelogs.
 * Supports free tier (template) and paid tier (LLM-powered summaries).
 *
 * Zero-touch design:
 * - GitHub App shared across fleet (users install via OAuth)
 * - Payment verified on-chain (USDC sent to fleet wallet)
 * - Changelog commits automated via GitHub App token
 */

import type { IncomingHttpHeaders } from 'http';
import { createHmac } from 'crypto';

export interface PRMergedEvent {
  action: 'closed';
  pull_request: {
    number: number;
    title: string;
    body: string;
    user: { login: string };
    labels: Array<{ name: string }>;
    merged: boolean;
    merged_at: string;
    html_url: string;
    head: { sha: string };
    base: { repo: { owner: { login: string }; name: string } };
  };
  repository: {
    owner: { login: string };
    name: string;
    full_name: string;
    default_branch: string;
  };
}

export interface ChangelogEntry {
  pr: number;
  title: string;
  labels: string[];
  author: string;
  url: string;
  mergedAt: string;
  summary?: string; // Paid tier only
  category?: 'feature' | 'fix' | 'breaking' | 'other';
}

export interface WebhookVerifyOptions {
  secret: string;
  payload: string;
  signature: string;
}

export interface ChangelogGeneratorOptions {
  isDryRun?: boolean;
  claudeApiKey?: string; // Only for paid tier
  fleetWalletAddress?: string;
  stateDb?: any; // SQLite database handle
}

/**
 * Verify GitHub webhook signature (HMAC-SHA256)
 */
export function verifyGitHubWebhookSignature({
  secret,
  payload,
  signature,
}: WebhookVerifyOptions): boolean {
  const hash = createHmac('sha256', secret)
    .update(payload)
    .digest('hex');

  const expectedSignature = `sha256=${hash}`;
  return expectedSignature === signature;
}

/**
 * Extract organization and repo from GitHub event
 */
export function extractRepoIdentifier(event: PRMergedEvent): {
  org: string;
  repo: string;
  fullName: string;
} {
  return {
    org: event.repository.owner.login,
    repo: event.repository.name,
    fullName: event.repository.full_name,
  };
}

/**
 * Check if repository has paid subscription
 * (In production, this queries state.db for on-chain verified payment)
 */
export async function isPaidRepo(
  org: string,
  repo: string,
  stateDb?: any
): Promise<boolean> {
  if (!stateDb) {
    // In production, query state.db:
    // SELECT * FROM changelog_subscriptions
    // WHERE org = ? AND repo = ? AND paid_until > NOW()
    return false; // Default to free tier for MVP
  }

  try {
    const row = stateDb.prepare(
      `SELECT paid_until FROM changelog_subscriptions
       WHERE org = ? AND repo = ? AND paid_until > datetime('now')`
    ).get(org, repo);
    return !!row;
  } catch {
    return false;
  }
}

/**
 * Generate free-tier changelog entry (template-based)
 */
export function generateFreeChangelogEntry(event: PRMergedEvent): ChangelogEntry {
  const pr = event.pull_request;
  const labels = pr.labels.map((l) => l.name);

  return {
    pr: pr.number,
    title: pr.title,
    labels,
    author: pr.user.login,
    url: pr.html_url,
    mergedAt: pr.merged_at,
  };
}

/**
 * Format changelog entry as Markdown
 */
export function formatChangelogEntryAsMarkdown(entry: ChangelogEntry): string {
  const labels = entry.labels.length > 0 ? ` ${entry.labels.map((l) => `\`${l}\``).join(' ')}` : '';
  const category = entry.category ? `**${entry.category.toUpperCase()}** ` : '';

  const line = `- ${category}[#${entry.pr}](${entry.url}): ${entry.title} (@${entry.author})${labels}`;

  if (entry.summary) {
    return `${line}\n  > ${entry.summary}`;
  }
  return line;
}

/**
 * Format changelog header with fleet attribution
 */
export function formatChangelogHeader(): string {
  return `# Changelog

All notable changes to this project will be documented in this file.

**Generated by [agent-changelog](https://github.com/rapartlu/agent-changelog)** — autonomous AI fleet. See [CHARTER](https://github.com/rapartlu/agent-orchestrator/blob/main/CHARTER.md) and [treasury](https://github.com/rapartlu/agent-orchestrator/blob/main/docs/treasury.md).

---
`;
}

/**
 * Build changelog content (prepend new entry to existing)
 */
export function buildChangelogContent(
  existingContent: string | null,
  newEntry: ChangelogEntry,
  eventDate: string
): string {
  const header = formatChangelogHeader();
  const entryLine = formatChangelogEntryAsMarkdown(newEntry);

  // Extract date (YYYY-MM-DD)
  const date = eventDate.split('T')[0];

  // Create date section
  const dateSection = `## [Unreleased] - ${date}\n\n${entryLine}\n`;

  if (!existingContent || existingContent.trim().length === 0) {
    return header + dateSection;
  }

  // Remove existing header, prepend new section
  const cleaned = existingContent
    .replace(/^# Changelog.*?---\n\n/ms, '') // Remove old header
    .replace(/^---\n\n/m, ''); // Remove separator if present

  return header + dateSection + '\n' + cleaned;
}

/**
 * Handler: Process PR merge event and update changelog
 *
 * Free tier: Generate template-based changelog
 * Paid tier: Add LLM-powered summary
 */
export async function handlePRMergedEvent(
  event: PRMergedEvent,
  options: ChangelogGeneratorOptions = {}
): Promise<{
  success: boolean;
  entry: ChangelogEntry;
  isPaid: boolean;
  error?: string;
}> {
  // Only process merged PRs
  if (!event.pull_request.merged) {
    return {
      success: false,
      entry: generateFreeChangelogEntry(event),
      isPaid: false,
      error: 'PR not merged',
    };
  }

  const { org, repo } = extractRepoIdentifier(event);
  const isPaid = await isPaidRepo(org, repo, options.stateDb);

  // Generate base entry
  let entry = generateFreeChangelogEntry(event);

  // If paid, add LLM summary (stub for now)
  if (isPaid && options.claudeApiKey) {
    entry.summary = '[Premium summary would be generated here via Claude API]';
    entry.category = 'feature'; // Would be determined by LLM
  }

  // In production:
  // 1. Fetch existing CHANGELOG.md from repo
  // 2. Build new changelog content
  // 3. Commit and push via GitHub App token
  // 4. Post comment to PR
  // 5. Notify Slack/Linear if configured

  if (!options.isDryRun) {
    // Stub: Real implementation would commit to repo
    console.log(`[agent-changelog] Would update ${org}/${repo} CHANGELOG.md for PR #${entry.pr}`);
  }

  return {
    success: true,
    entry,
    isPaid,
  };
}

/**
 * Express/Node.js middleware for GitHub webhook
 *
 * Usage:
 * ```typescript
 * app.post('/github/webhook', changelogWebhookHandler(webhookSecret, options));
 * ```
 */
export function createChangelogWebhookHandler(
  webhookSecret: string,
  options: ChangelogGeneratorOptions = {}
) {
  return async (
    req: { body: PRMergedEvent; headers: IncomingHttpHeaders; rawBody?: string },
    res: { status: (code: number) => { json: (obj: any) => void } }
  ) => {
    try {
      // Verify webhook signature
      const signature = req.headers['x-hub-signature-256'] as string;
      const payload = req.rawBody || JSON.stringify(req.body);

      if (!verifyGitHubWebhookSignature({ secret: webhookSecret, payload, signature })) {
        return res.status(401).json({ error: 'Invalid signature' });
      }

      // Only process PR merge events
      if (req.headers['x-github-event'] !== 'pull_request') {
        return res.status(200).json({ ignored: 'Not a PR event' });
      }

      const event = req.body as PRMergedEvent;
      if (event.action !== 'closed' || !event.pull_request.merged) {
        return res.status(200).json({ ignored: 'PR not merged' });
      }

      // Process changelog
      const result = await handlePRMergedEvent(event, options);

      return res.status(200).json({
        success: result.success,
        entry: result.entry,
        isPaid: result.isPaid,
      });
    } catch (error) {
      console.error('[agent-changelog] Webhook error:', error);
      return res.status(500).json({ error: 'Internal server error' });
    }
  };
}

/**
 * CLI: Generate changelog for existing repo (backfill)
 */
export async function backfillChangelog(
  org: string,
  repo: string,
  prNumbers: number[],
  options: ChangelogGeneratorOptions = {}
): Promise<{
  success: boolean;
  entriesGenerated: number;
  error?: string;
}> {
  // In production: Fetch PR metadata via GitHub API, generate changelog entries
  console.log(
    `[agent-changelog] Backfilling ${org}/${repo} for ${prNumbers.length} PRs (stub)`
  );

  return {
    success: true,
    entriesGenerated: prNumbers.length,
  };
}

/**
 * Monitor fleet wallet for incoming payments
 * (Runs periodically, verifies paid subscriptions)
 */
export async function pollPaymentsFromWallet(
  fleetWalletAddress: string,
  rpcUrl: string,
  stateDb?: any
): Promise<{
  newPayments: number;
  subscriptionsUpdated: number;
  error?: string;
}> {
  // In production:
  // 1. Connect to Base RPC (Alchemy, Infura, public RPC)
  // 2. Query recent transactions to fleetWalletAddress
  // 3. Parse memo field for "agent-changelog:org/repo"
  // 4. Verify USDC/DAI transfer amount ($5 or $20)
  // 5. Update state.db changelog_subscriptions table
  // 6. Set paid_until = NOW() + 1 month

  console.log(
    `[agent-changelog] Would poll ${fleetWalletAddress} on Base for payments (stub)`
  );

  return {
    newPayments: 0,
    subscriptionsUpdated: 0,
  };
}
