#!/usr/bin/env node

import { Command } from "commander";
import { registerAgentsCommand } from "./commands/agents.js";
import { registerDispatchCommand } from "./commands/dispatch.js";
import { registerAskCommand } from "./commands/ask.js";
import { registerStatusCommand } from "./commands/status.js";
import { registerServiceCommand } from "./commands/service.js";
import { registerImproveCommand } from "./commands/improve.js";
import { registerSuperviseCommand } from "./commands/supervise.js";
import { registerReviewCommand } from "./commands/review.js";
import { registerCreateCommand } from "./commands/create.js";
import { registerPRsCommand } from "./commands/prs.js";
import { registerResearchCommand } from "./commands/research.js";
import { registerHealthCommand } from "./commands/health.js";
import { registerMetricsCommand } from "./commands/metrics.js";
import { registerGuardHealthCommand } from "./commands/guard.js";
import { registerReliabilityCommand } from "./commands/reliability.js";
import { registerPreflightCommand } from "./commands/preflight.js";
import { registerAuditCommand } from "./commands/audit.js";
import { registerDigestCommand } from "./commands/digest.js";
import { registerTimeoutsCommand } from "./commands/timeouts.js";
import { registerDirectivesCommand } from "./commands/directives.js";
import { registerDeescalateCommand } from "./commands/deescalate.js";
import { registerPRResetCommand } from "./commands/pr-reset.js";
import { registerDecisionsCommand } from "./commands/decisions.js";
import { registerBudgetCommand } from "./commands/budget.js";
import { registerIssueStatusCommand } from "./commands/issue-status.js";
import { registerDispatchEfficiencyCommand } from "./commands/dispatch-efficiency.js";
import { registerSupervisorLogCommand } from "./commands/supervisor-log.js";
import { registerConfigCommand } from "./commands/config.js";
import { registerBorrowCommand } from "./commands/borrow.js";
import { registerFleetCommand } from "./commands/fleet.js";
import { registerLearnedRulesCommand } from "./commands/learned-rules.js";
import { registerAuditInfraCommand } from "./commands/audit-infra.js";
import { registerRoutingAccuracyCommand } from "./commands/routing-accuracy.js";
import { registerSignalsCommand } from "./commands/signals.js";
import { registerLearnedPatternsCommand } from "./commands/learned-patterns.js";
import { registerAgentGapsCommand } from "./commands/agent-gaps.js";
import { registerMonologueCommand } from "./commands/monologue.js";
import { registerLineageCommand } from "./commands/lineage.js";
import { registerAntibodiesCommand } from "./commands/antibodies.js";
import { registerHealthCheckEfficiencyCommand } from "./commands/health-check-efficiency.js";
import { registerHealthChecksCommand } from "./commands/health-checks.js";
import { registerCostCommand } from "./commands/cost.js";
import { registerSkipBlockersCommand } from "./commands/skip-blockers.js";
import { registerFollowupChainsCommand } from "./commands/followup-chains.js";
import { registerRoutingMismatchesCommand } from "./commands/routing-mismatches.js";
import { registerReviewSaturationCommand } from "./commands/review-saturation.js";
import { registerMemoryCommand } from "./commands/memory.js";
import { registerControlsCommand } from "./commands/controls.js";
import { registerDagCommand } from "./commands/dag.js";
import { registerFailureInterceptionsCommand } from "./commands/failure-interceptions.js";
import { registerStandupQualityCommand } from "./commands/standup-quality.js";
import { registerMarginalScoreTasksCommand } from "./commands/marginal-score-tasks.js";
import { registerAnomaliesCommand } from "./commands/anomalies.js";
import { registerDispatchHangWatchCommand } from "./commands/dispatch-hang-watch.js";
import { registerExternalImpactCommand } from "./commands/external-impact.js";
import { registerPublishStandupCommand } from "./commands/publish-standup.js";
import { registerMergeSweepCommand } from "./commands/merge-sweep.js";
import { registerTreasuryCommand } from "./commands/treasury.js";
import { registerBountyCommand } from "./commands/bounty.js";
import { registerSecurityExemptionsCommand } from "./commands/security-exemptions.js";
import { registerSubmissionCommand } from "./commands/submission.js";
import { registerRevenueLeadCommand } from "./commands/revenue-leads.js";
import { registerDMOutreachCommand } from "./commands/dm-outreach.js";
import { registerConnectionErrorsCommand } from "./commands/connection-errors.js";
import { registerGoalsSnapshotCommand } from "./commands/goals-snapshot.js";
import { registerDnsCommand } from "./commands/dns.js";

const program = new Command();

program
  .name("orch")
  .description("Orchestrator for Claude Code agent directories")
  .version("0.1.0")
  .option("-c, --config <path>", "Path to agents.yaml config file");

// Commands read configPath from program.opts() at execution time
registerAgentsCommand(program);
registerDispatchCommand(program);
registerAskCommand(program);
registerStatusCommand(program);
registerServiceCommand(program);
registerImproveCommand(program);
registerSuperviseCommand(program);
registerReviewCommand(program);
registerCreateCommand(program);
registerPRsCommand(program);
registerResearchCommand(program);
registerHealthCommand(program);
registerMetricsCommand(program);
registerGuardHealthCommand(program);
registerReliabilityCommand(program);
registerPreflightCommand(program);
registerAuditCommand(program);
registerDigestCommand(program);
registerTimeoutsCommand(program);
registerDirectivesCommand(program);
registerDeescalateCommand(program);
registerPRResetCommand(program);
registerDecisionsCommand(program);
registerBudgetCommand(program);
registerIssueStatusCommand(program);
registerDispatchEfficiencyCommand(program);
registerSupervisorLogCommand(program);
registerConfigCommand(program);
registerBorrowCommand(program);
registerFleetCommand(program);
registerLearnedRulesCommand(program);
registerAuditInfraCommand(program);
registerRoutingAccuracyCommand(program);
registerRoutingMismatchesCommand(program);
registerSignalsCommand(program);
registerLearnedPatternsCommand(program);
registerLineageCommand(program);
registerMonologueCommand(program);
registerAntibodiesCommand(program);
registerHealthCheckEfficiencyCommand(program);
registerHealthChecksCommand(program);
registerCostCommand(program);
registerAgentGapsCommand(program);
registerSkipBlockersCommand(program);
registerFollowupChainsCommand(program);
registerReviewSaturationCommand(program);
registerMemoryCommand(program);
registerControlsCommand(program);
registerDagCommand(program);
registerFailureInterceptionsCommand(program);
registerStandupQualityCommand(program);
registerMarginalScoreTasksCommand(program);
registerAnomaliesCommand(program);
registerDispatchHangWatchCommand(program);
registerExternalImpactCommand(program);
registerPublishStandupCommand(program);
registerMergeSweepCommand(program);
registerTreasuryCommand(program);
registerBountyCommand(program);
registerSecurityExemptionsCommand(program);
registerSubmissionCommand(program);
registerRevenueLeadCommand(program);
registerDMOutreachCommand(program);
registerConnectionErrorsCommand(program);
registerGoalsSnapshotCommand(program);
registerDnsCommand(program);

program.parse();
// docs PR ci-trigger
