/**
 * Review API Service
 *
 * Wraps the existing `PRReviewer` class with:
 *   - API-key authentication
 *   - Billing tier enforcement (free/basic/pro)
 *   - Usage tracking in `review_api_usage`
 *   - A structured JSON response format for external callers
 *
 * Article IV compliance: all review outputs include the mandatory AI disclosure
 * notice identifying the review as generated by the autonomous AI fleet.
 *
 * ## Endpoint contract
 *
 *   POST /review
 *   Authorization: Bearer rr_<tier>_<client-uuid>
 *   Content-Type:  application/json
 *
 *   Body:  { "pr_url": "https://github.com/owner/repo/pull/42" }
 *
 *   Response 200:
 *   {
 *     "decision":     "approve" | "request-changes" | "escalate",
 *     "comment":      string,
 *     "reason":       string,
 *     "score":        number | null,        // null on free tier
 *     "tier":         "free" | "basic" | "pro",
 *     "inline_comments": [...] | null,      // pro tier only
 *     "security_findings": [...] | null,    // pro tier only
 *     "remaining_reviews": number | -1,
 *     "disclosure":   string,               // Article IV AI authorship notice
 *     "reviewed_at":  string                // ISO-8601
 *   }
 *
 *   Error responses follow the same envelope:
 *   { "error": string, "code": string }
 */

import Database from "better-sqlite3";
import { createLogger } from "../service/logger.js";
import type { ReviewerConfig } from "../config.js";
import { CANONICAL_WALLET_ADDRESS } from "../service/survival-plan.js";
import {
  parseTierFromApiKey,
  clientIdFromApiKey,
  checkBillingAllowance,
  TIER_CONFIGS,
  type ReviewTier,
} from "./review-api-billing.js";
import {
  ensureReviewApiUsageTable,
  recordReviewUsage,
  getMonthlyUsageCount,
} from "./review-api-usage.js";

const logger = createLogger("review-api-service");

/** Article IV AI authorship disclosure (mandatory on all outputs). */
export const ARTICLE_IV_DISCLOSURE =
  "Review generated by autonomous AI fleet claude-agent-orchestrator. " +
  "This review is produced by an AI system and should be considered alongside human judgment.";

export interface ReviewApiRequest {
  /** Full GitHub PR URL, e.g. https://github.com/owner/repo/pull/42 */
  pr_url: string;
  /**
   * Optional override for how deeply to scan. Defaults to the maximum allowed
   * by the caller's billing tier.
   */
  review_depth?: "basic" | "deep";
}

export interface SecurityFinding {
  severity: "low" | "medium" | "high" | "critical";
  file?: string;
  line?: number;
  message: string;
}

export interface InlineComment {
  file: string;
  line: number;
  comment: string;
}

export interface ReviewApiResponse {
  decision: "approve" | "request-changes" | "escalate";
  comment: string;
  reason: string;
  /** Quality score 0–1, null on free tier. */
  score: number | null;
  tier: ReviewTier;
  inline_comments: InlineComment[] | null;
  security_findings: SecurityFinding[] | null;
  /** Remaining reviews this month, -1 for unlimited. */
  remaining_reviews: number;
  disclosure: string;
  reviewed_at: string;
}

export interface ReviewApiError {
  error: string;
  code: string;
}

/**
 * Parse a GitHub PR URL into { owner, repo, prNumber }.
 * Returns null if the URL cannot be parsed.
 */
export function parsePrUrl(
  prUrl: string
): { owner: string; repo: string; prNumber: number } | null {
  const match =
    /^https?:\/\/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/.exec(prUrl);
  if (!match) return null;
  return {
    owner: match[1],
    repo: match[2],
    prNumber: parseInt(match[3], 10),
  };
}

/** Build the `owner/repo` string from a PR URL, or null. */
export function repoFromPrUrl(prUrl: string): string | null {
  const parsed = parsePrUrl(prUrl);
  return parsed ? `${parsed.owner}/${parsed.repo}` : null;
}

export interface ReviewApiServiceOptions {
  /** Path to the SQLite state.db. Defaults to ./state.db */
  dbPath?: string;
  /**
   * Optional reviewer config override. When omitted the service reads from the
   * environment / default config location.
   */
  reviewerConfig?: Partial<ReviewerConfig>;
}

/**
 * Core service class for the PR review API.
 *
 * Callers authenticate via a Bearer API key formatted as:
 *   `rr_<tier>_<client-uuid>`
 *
 * The tier is extracted from the key prefix; no separate lookup is required
 * for the MVP. A production deployment would validate the key against a DB
 * and look up the active Polar.sh subscription.
 */
export class ReviewApiService {
  private db: Database.Database;

  constructor(private readonly options: ReviewApiServiceOptions = {}) {
    const dbPath = options.dbPath ?? process.env.STATE_DB_PATH ?? "./state.db";
    this.db = new Database(dbPath);
    ensureReviewApiUsageTable(this.db);
    logger.info("ReviewApiService initialised", { dbPath });
  }

  /**
   * Handle an incoming review request.
   *
   * @param apiKey  Bearer token from the Authorization header.
   * @param request Request body.
   * @returns ReviewApiResponse on success, ReviewApiError on failure.
   */
  async handleReview(
    apiKey: string | undefined,
    request: ReviewApiRequest
  ): Promise<ReviewApiResponse | ReviewApiError> {
    // --- Authentication ---
    if (!apiKey) {
      return {
        error: "Missing Authorization header. Provide: Authorization: Bearer rr_<tier>_<key>",
        code: "MISSING_AUTH",
      };
    }

    const tier = parseTierFromApiKey(apiKey);
    const clientId = clientIdFromApiKey(apiKey);
    const tierConfig = TIER_CONFIGS[tier];

    // --- Billing check ---
    const usageThisMonth = getMonthlyUsageCount(this.db, clientId);
    const billingCheck = checkBillingAllowance(tier, usageThisMonth);

    if (!billingCheck.allowed) {
      logger.warn("Review blocked: tier limit reached", {
        clientId,
        tier,
        usageThisMonth,
      });
      return {
        error: billingCheck.reason ?? "Monthly review limit reached.",
        code: "TIER_LIMIT_REACHED",
      };
    }

    // --- PR URL validation ---
    const parsed = parsePrUrl(request.pr_url);
    if (!parsed) {
      return {
        error: "Invalid pr_url. Expected: https://github.com/owner/repo/pull/N",
        code: "INVALID_PR_URL",
      };
    }

    const repo = `${parsed.owner}/${parsed.repo}`;
    const reviewDepth: "basic" | "deep" =
      request.review_depth ??
      (tierConfig.deepSecurityScan ? "deep" : "basic");

    // Deep reviews require pro tier
    if (reviewDepth === "deep" && !tierConfig.deepSecurityScan) {
      return {
        error: "Deep security scan requires Pro tier ($49/mo). Upgrade at https://polar.sh.",
        code: "TIER_FEATURE_GATED",
      };
    }

    // --- Perform review via PRReviewer ---
    const startMs = Date.now();
    let reviewResult: {
      decision: "approve" | "request-changes" | "escalate";
      comment: string;
      reason: string;
      confidence?: number | null;
    };

    try {
      // Dynamic import to avoid hard coupling reviewer config at module load
      const { PRReviewer } = await import("./pr-reviewer.js");
      const { loadConfig } = await import("../config/schema.js");
      const { StateStore } = await import("../state/store.js");
      const config = loadConfig();
      const store = new StateStore(this.options.dbPath);
      const reviewer = new PRReviewer(
        { ...config, ...(this.options.reviewerConfig ?? {}) },
        store
      );
      reviewResult = await reviewer.reviewPR(repo, parsed.prNumber);
    } catch (err) {
      logger.error("PRReviewer threw during API review", {
        repo,
        pr: parsed.prNumber,
        err,
      });
      return {
        error: "Review failed due to an internal error. Please retry.",
        code: "REVIEW_FAILED",
      };
    }

    const durationMs = Date.now() - startMs;

    // --- Build structured response ---
    const score = tierConfig.qualityScore
      ? (reviewResult.confidence ?? null)
      : null;

    const inlineComments: InlineComment[] | null = tierConfig.inlineComments
      ? extractInlineComments(reviewResult.comment)
      : null;

    const securityFindings: SecurityFinding[] | null =
      tierConfig.deepSecurityScan
        ? extractSecurityFindings(reviewResult.comment)
        : null;

    const reviewedAt = new Date().toISOString();

    // --- Record usage ---
    recordReviewUsage(this.db, {
      client_id: clientId,
      tier,
      pr_url: request.pr_url,
      repo,
      review_type: reviewDepth,
      score,
      duration_ms: durationMs,
      created_at: reviewedAt,
    });

    // Recompute remaining after recording
    const updatedUsage = getMonthlyUsageCount(this.db, clientId);
    const remaining =
      tierConfig.monthlyLimit === -1
        ? -1
        : Math.max(0, tierConfig.monthlyLimit - updatedUsage);

    logger.info("Review completed", {
      clientId,
      tier,
      repo,
      pr: parsed.prNumber,
      decision: reviewResult.decision,
      durationMs,
    });

    return {
      decision: reviewResult.decision,
      comment: reviewResult.comment,
      reason: reviewResult.reason,
      score,
      tier,
      inline_comments: inlineComments,
      security_findings: securityFindings,
      remaining_reviews: remaining,
      disclosure: ARTICLE_IV_DISCLOSURE,
      reviewed_at: reviewedAt,
    };
  }

  /** List tiers and pricing for the /pricing endpoint. */
  getPricingInfo(): {
    tiers: typeof TIER_CONFIGS;
    payment: {
      wallet_address: string;
      network: string;
      tokens_accepted: string[];
      polar_url: string;
      note: string;
    };
  } {
    return {
      tiers: TIER_CONFIGS,
      payment: {
        wallet_address: process.env.FLEET_WALLET_ADDRESS ?? CANONICAL_WALLET_ADDRESS,
        network: "Base (L2, Ethereum-compatible)",
        tokens_accepted: ["USDC", "DAI", "ETH", "ERC-20"],
        polar_url: process.env.FLEET_POLAR_URL ?? "https://polar.sh",
        note: "Send USDC/DAI on Base network directly to wallet_address, or subscribe via Polar.sh.",
      },
    };
  }

  close(): void {
    this.db.close();
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Extract inline comment blocks from a review comment string.
 * Looks for lines matching the pattern:
 *   `file.ts:42: <message>`
 * Returns null if no inline-style comments are found.
 */
function extractInlineComments(comment: string): InlineComment[] | null {
  const pattern = /^([^\s:]+):(\d+):\s+(.+)$/gm;
  const results: InlineComment[] = [];
  let m: RegExpExecArray | null;
  while ((m = pattern.exec(comment)) !== null) {
    results.push({ file: m[1], line: parseInt(m[2], 10), comment: m[3] });
  }
  return results.length > 0 ? results : null;
}

/**
 * Extract security findings from a review comment string.
 * Looks for lines containing security severity keywords.
 */
function extractSecurityFindings(comment: string): SecurityFinding[] | null {
  const severityPattern =
    /\b(critical|high|medium|low)\b.*?(security|vuln|injection|xss|csrf|secret|credential|token|leak)/gi;
  const results: SecurityFinding[] = [];
  const lines = comment.split("\n");

  for (const line of lines) {
    const m = severityPattern.exec(line);
    if (m) {
      results.push({
        severity: m[1].toLowerCase() as SecurityFinding["severity"],
        message: line.trim(),
      });
    }
    severityPattern.lastIndex = 0; // reset stateful regex
  }

  return results.length > 0 ? results : null;
}
